package com.scandit.reactnative

const val COMMAND_START_SCANNING = 0
const val COMMAND_START_SCANNING_IN_PAUSED_STATE = 1
const val COMMAND_STOP_SCANNING = 2
const val COMMAND_RESUME_SCANNING = 3
const val COMMAND_PAUSE_SCANNING = 4
const val COMMAND_APPLY_SETTINGS = 5
const val COMMAND_VIEWFINDER_DIMENSION = 6
const val COMMAND_BEEP_ENABLED = 7
const val COMMAND_VIBRATE_ENABLED = 8
const val COMMAND_TORCH_ENABLED = 9
const val COMMAND_TORCH_BUTTON_MARGINS_AND_SIZE = 10
const val COMMAND_CAMERA_SWITCH_VISIBILITY = 11
const val COMMAND_CAMERA_SWITCH_MARGINS_AND_SIZE = 12
const val COMMAND_VIEWFINDER_COLOR = 13
const val COMMAND_VIEWFINDER_DECODED_COLOR = 14
const val COMMAND_MATRIX_HIGHLIGHT_COLOR = 15
const val COMMAND_SET_OVERLAY_PROPERTY = 16
const val COMMAND_SET_GUI_STYLE = 17
const val COMMAND_SET_TEXT_RECOGNITION_SWITCH_ENABLED = 18
const val COMMAND_FINISH_ON_SCAN_CALLBACK = 19
const val COMMAND_FINISH_ON_RECOGNIZE_NEW_CODES_CALLBACK = 20
const val COMMAND_SWITCH_TORCH_ON = 21
const val COMMAND_FINISH_ON_CHANGE_TRACKED_CODES_CALLBACK = 22
